oauthServer: his is afladksflasfkladsjlkfdr   dev

spring:
  datasource:
    platform: org.hibernate.dialect.MySQL5Dialect
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth_demo
    username: root
    password: root

app:
  auth:
    resourceId: OAUTH_DEMO
    defaultAccessTokenTimeout: 1800
    defaultRefreshTokenTimeout: 86400
    kfName: demo.jks
    ksPass: Za6{ApH5S}W4Pud
    maxFailedLoginAttemptsForAccountLock: 5
    failedLoginAttemptAccountLockTimeout: 900
  endpoint:
    api: /api
    index: ${app.endpoint.api}/index
    testEndpoint: ${app.endpoint.api}/testAuth
